version: '3'

services:
  mysqldb:
    image: 'mysql'
    restart: always
    container_name: 'java-mysqldb'
    environment:
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=empus
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345

  app:
    build: ./
    container_name: 'java-app'
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb